Repository arjuaman/hacktoberfest2021, pull requests merged in 2021-10, with the labels that each got.

#20 kadanes(maximum sub array sum) algorithm c++
  kadanes.cpp
Labels: hacktoberfest, beginner, hacktoberfest-accepted

#21 Finding friends
  Java/Finding Friends/Solution.java
  Java/Finding Friends/ques.txt
Labels: hacktoberfest, beginner, hacktoberfest-accepted, hacktoberfest-2021

#22 isSubsequence
  Java/isSubsequence/Solution.java
  Java/isSubsequence/ques.txt
Labels: hacktoberfest, beginner, hacktoberfest-accepted, hacktoberfest-2021

#23 Prog3
  Java/Partition Array into Disjoint Intervals/Solution.java
  Java/Partition Array into Disjoint Intervals/ques.txt
Labels: hacktoberfest, beginner, hacktoberfest-accepted, hacktoberfest-2021

#24 prog4
  Java/Maximum Subarray/Solution.java
  Java/Maximum Subarray/ques.txt
Labels: hacktoberfest, beginner, hacktoberfest-accepted, hacktoberfest-2021

#25 edit distance program
  Java/Edit Distance/Solution.java
  Java/Edit Distance/ques.txt
Labels: hacktoberfest, hacktoberfest-accepted

#26 kclosestElement.cpp
  C++/kclosestElement.cpp
Labels: hacktoberfest-accepted

#28 Program to Time Difference
  C++/Program to Time Difference
Labels: hacktoberfest-accepted

#29 Create reverse_an_array_in_groups_of_given_size.cpp
  C++/reverse_an_array_in_groups_of_given_size.cpp
Labels: hacktoberfest, hacktoberfest-accepted
